package keymap

// Default bindings, copied from rmpc's default config. MPD-only actions
// (outputs, decoders, partitions, downloads, ratings) are omitted. "S",
// "oc" and navigation "X" are EncomPlayer additions on keys rmpc leaves
// free; "oc" joins rmpc's o-prefixed "show" family.
var defaultBindings = map[Context]map[string]string{
	Global: {
		"q":       Quit,
		"?":       ShowHelp,
		":":       CommandMode,
		"oI":      ShowCurrentSongInfo,
		"z":       ToggleRepeat,
		"x":       ToggleRandom,
		"c":       ToggleConsume,
		"v":       ToggleSingle,
		"p":       TogglePause,
		"s":       Stop,
		">":       NextTrack,
		"<":       PreviousTrack,
		"f":       SeekForward,
		"b":       SeekBack,
		".":       VolumeUp,
		",":       VolumeDown,
		"<Tab>":   NextTab,
		"gt":      NextTab,
		"<S-Tab>": PreviousTab,
		"gT":      PreviousTab,
		"1":       `SwitchToTab("Queue")`,
		"2":       `SwitchToTab("Directories")`,
		"3":       `SwitchToTab("Artists")`,
		"4":       `SwitchToTab("Album Artists")`,
		"5":       `SwitchToTab("Albums")`,
		"6":       `SwitchToTab("Playlists")`,
		"7":       `SwitchToTab("Search")`,
		"8":       `SwitchToTab("Genres")`,
		"<C-u>":   Update,
		"<C-U>":   Rescan,
		"R":       AddRandom,
		"S":       ShuffleAll,
		"oc":      ShowConfig,
	},
	Navigation: {
		"<C-c>":      Close,
		"<Esc>":      Close,
		"<CR>":       Confirm,
		"k":          Up,
		"<Up>":       Up,
		"j":          Down,
		"<Down>":     Down,
		"h":          Left,
		"<Left>":     Left,
		"l":          Right,
		"<Right>":    Right,
		"<C-w>k":     PaneUp,
		"<C-Up>":     PaneUp,
		"<C-w>j":     PaneDown,
		"<C-Down>":   PaneDown,
		"<C-w>h":     PaneLeft,
		"<C-Left>":   PaneLeft,
		"<C-w>l":     PaneRight,
		"<C-Right>":  PaneRight,
		"K":          MoveUp,
		"J":          MoveDown,
		"<C-u>":      UpHalf,
		"<C-d>":      DownHalf,
		"<C-b>":      PageUp,
		"<PageUp>":   PageUp,
		"<C-f>":      PageDown,
		"<PageDown>": PageDown,
		"gg":         Top,
		"G":          Bottom,
		"<Space>":    Select,
		"<C-Space>":  InvertSelection,
		"/":          EnterSearch,
		"n":          NextResult,
		"N":          PreviousResult,
		"a":          Add,
		"A":          AddAll,
		"D":          Delete,
		"<C-r>":      Rename,
		"i":          FocusInput,
		"oi":         ShowInfo,
		"<C-s>s":     Save,
		"<C-s>a":     SaveAll,
		"X":          ShufflePlay,
	},
	Queue: {
		"d":    Delete,
		"D":    DeleteAll,
		"<CR>": Play,
		"C":    JumpToCurrent,
		"X":    Shuffle,
	},
}
